// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9dAc7NCeFAjy8MQzEjgHcxwcV4fUBv4c',
    appId: '1:546548502432:web:b0c3930a9ff62b45f91ec5',
    messagingSenderId: '546548502432',
    projectId: 'psyched-timer-470611-r2',
    authDomain: 'psyched-timer-470611-r2.firebaseapp.com',
    storageBucket: 'psyched-timer-470611-r2.firebasestorage.app',
    measurementId: 'G-J30QJCHVTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV8RBskbMcEHZ055o7HxJrqtRTF4IAI0o',
    appId: '1:546548502432:android:5a1464f2864c2221f91ec5',
    messagingSenderId: '546548502432',
    projectId: 'psyched-timer-470611-r2',
    storageBucket: 'psyched-timer-470611-r2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR7SaT7wUw6PTlGy47GG2xS8MyRcMJqzw',
    appId: '1:546548502432:ios:69bb60f4d52a5768f91ec5',
    messagingSenderId: '546548502432',
    projectId: 'psyched-timer-470611-r2',
    storageBucket: 'psyched-timer-470611-r2.firebasestorage.app',
    iosBundleId: 'konstant.com.konstant',
  );
}
